name: 自动同步Apple增强仓库

on:
  schedule:
    - cron: '0 0 * * *'  # 每天凌晨 0 点触发，可以根据需要调整时间
  workflow_dispatch:  # 手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取自己的仓库
        uses: actions/checkout@v2
        with:
          repository: halfteas/apple # 替换为你的仓库 B
          token: ${{ secrets.SURGE_APPLE }}

      - name: 拉取Apple增强仓库并同步
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote add repoA https://github.com/VirgilClyne/iRingo.git
          git fetch repoA
          git merge repoA/main -X theirs --allow-unrelated-histories -m "sync: merge changes from repoA"
          git push origin main
